"""
Design-stage power analysis.

This is the one part of the project that produces genuine numbers before a
single match has been annotated, and it is the part that should be run first.
It answers the only question that matters at the start: how many zone
transitions must be annotated by hand before each hypothesis can be separated?

The answer varies by two orders of magnitude across the battery, which is the
whole argument for sequencing the work rather than collecting "as many matches
as possible" and hoping. Annotating a transition costs a few minutes of human
attention; knowing that one test needs 12 observations and another needs 400
decides what to do this week.

Nothing here is an empirical claim about PUBG Mobile. It is a statement about
the tests: given data generated by hypothesis X, how often does the battery
correctly reject the uniform-disc null at alpha?
"""

from __future__ import annotations

import numpy as np

from .generative import (
    AdmissibleDiscModel,
    CoupledSpiralModel,
    EdgeBiasedDiscModel,
    RadiusSchedule,
    UniformMapModel,
)
from .geometry import Circle, TWO_PI
from .tests_stats import (
    bearing_kuiper_test,
    coupling_test,
    independence_test,
    radial_uniformity_test,
)


def _simulate_transitions(model, n: int, rng, schedule: RadiusSchedule | None = None):
    """Draw n independent transitions and return their (s, theta) coordinates.

    Phases are drawn at random so that the simulated dataset resembles a real
    annotation pass across matches rather than one long single match.
    """
    schedule = schedule or RadiusSchedule()
    radii = schedule.radii()
    s_out = np.empty(n)
    th_out = np.empty(n)

    phases = rng.integers(0, len(radii) - 1, size=n)
    for i, ph in enumerate(phases):
        r_prev, r_next = radii[ph], radii[ph + 1]
        # Place the current circle somewhere legal on the map.
        c = rng.uniform(r_prev, 1 - r_prev, size=2) if r_prev < 0.5 else np.array([0.5, 0.5])
        prev = Circle(c[0], c[1], r_prev)
        pt = model.sample_centres(prev, r_next, 1, rng)[0]
        delta = pt - prev.centre
        R = r_prev - r_next
        d = float(np.hypot(*delta))
        s_out[i] = (d / R) ** 2 if R > 0 else np.nan
        th_out[i] = float(np.arctan2(delta[1], delta[0]) % TWO_PI)

    ok = np.isfinite(s_out)
    return s_out[ok], th_out[ok]


def power_curve(
    truth,
    test_name: str,
    sample_sizes=(10, 20, 30, 50, 100, 200, 400),
    n_trials: int = 300,
    alpha: float = 0.05,
    seed: int = 12345,
) -> dict[int, float]:
    """Rejection rate of one test at alpha, when data really come from `truth`."""
    rng = np.random.default_rng(seed)
    out: dict[int, float] = {}

    for n in sample_sizes:
        rejects = 0
        for _ in range(n_trials):
            s, th = _simulate_transitions(truth, n, rng)
            if len(s) < 5:
                continue
            if test_name == "coupling":
                res = coupling_test(s, th)
            elif test_name == "radial":
                res = radial_uniformity_test(s)
            elif test_name == "kuiper":
                res = bearing_kuiper_test(th, n_boot=400, seed=int(rng.integers(1 << 30)))
            elif test_name == "independence":
                res = independence_test(s, th)
            else:
                raise ValueError(f"unknown test {test_name}")
            if res.p_value is not None and res.p_value < alpha:
                rejects += 1
        out[n] = rejects / n_trials
    return out


def sample_size_table(n_trials: int = 300, seed: int = 7) -> str:
    """Build the design table that decides the annotation budget."""
    scenarios = [
        ("shared-draw spiral (patent literal reading)", CoupledSpiralModel(), "coupling"),
        ("half-plane bearings", AdmissibleDiscModel(angle_span=np.pi), "kuiper"),
        ("mild pull toward previous centre", EdgeBiasedDiscModel(a=0.7, b=1.0), "radial"),
        ("strong pull toward previous centre", EdgeBiasedDiscModel(a=0.45, b=1.0), "radial"),
        ("mild pull toward the rim", EdgeBiasedDiscModel(a=1.0, b=0.7), "radial"),
        ("no previous-circle constraint", UniformMapModel(), "radial"),
        ("true uniform disc (false-positive rate)", AdmissibleDiscModel(), "radial"),
    ]
    sizes = (10, 20, 30, 50, 100, 200, 400)

    lines = [
        "| Scenario | Test | " + " | ".join(f"n={n}" for n in sizes) + " |",
        "|---|---|" + "---|" * len(sizes),
    ]
    for label, model, test in scenarios:
        curve = power_curve(model, test, sizes, n_trials=n_trials, seed=seed)
        cells = " | ".join(f"{curve[n]:.2f}" for n in sizes)
        lines.append(f"| {label} | {test} | {cells} |")
    return "\n".join(lines)


def minimum_n(curve: dict[int, float], target: float = 0.8) -> int | None:
    """Smallest simulated n reaching the target power, or None if never."""
    for n in sorted(curve):
        if curve[n] >= target:
            return n
    return None


if __name__ == "__main__":  # pragma: no cover
    print(sample_size_table())
