export type Section = { title: string; blocks: Block[] };
export type Block = { kind: 'p' | 'rule' | 'fail' | 'h' | 'li'; text: string };

export const PLAYBOOK: Section[] = [
  {
    title: '2026 map pool',
    blocks: [
      { kind: 'p', text: 'The tier-1 pool is three maps, not five or six. PMGO Season 1 ran three matches on Erangel, two on Miramar and one on Rondo per day. PMWC 2026 in Paris ran the same split. Sanhok and Vikendi are not in the rotation, and PMSL events were removed for 2026 — the ladder now runs National Championships into PMGO S1, PMGO S2, PMWC and PMGC.' },
      { kind: 'rule', text: 'Split scrim time roughly 3 : 2 : 1 across Erangel, Miramar and Rondo. Time on Sanhok is time on a map nobody will score you on.' },
      { kind: 'p', text: 'Regional formats can differ. Confirm against the official rules pack for your specific event.' },
    ],
  },
  {
    title: 'Anti-rush defence',
    blocks: [
      { kind: 'p', text: 'A rush succeeds because the attacker knows when the fight starts and the defender finds out. Everything below buys back that half-second, or makes it not matter.' },
      { kind: 'h', text: 'A. Crossfire hold' },
      { kind: 'p', text: 'Never put four players in one building. Split 2–2 across two structures whose entrances cover each other. The test: if one grenade can hit both pairs, you have built one position with a gap, not two positions.' },
      { kind: 'fail', text: 'Both pairs holding the same approach. Crossfire means different angles on one lane.' },
      { kind: 'h', text: 'B. Layered defence' },
      { kind: 'p', text: 'One player sits wide as an outer marker. His job is not to win — it is to call the rush direction three to five seconds early and fall back. That window is the whole difference between a defended compound and a lost one.' },
      { kind: 'fail', text: 'The outer player tries to trade, dies, gives no callout. Now you are 3v4 and surprised.' },
      { kind: 'h', text: 'C. Utility denial' },
      { kind: 'p', text: 'Throw at the ground they must cross, not at the players. Molotov the entry, not the enemy — a molly in a doorway costs five seconds and forces a route you are already aimed at. Smoke your own position to break an angle they have, not theirs. Cook frags into the cover they are behind.' },
      { kind: 'fail', text: 'Saving utility for a fight that never comes. Grenades you carry to the final circle scored nothing.' },
      { kind: 'h', text: 'D. Pre-aim discipline' },
      { kind: 'p', text: 'At close range the player already aimed at the doorway wins the overwhelming majority of duels — reaction time plus the raise-and-aim animation is a gap nobody out-aims. Assign each player exactly one angle and forbid scanning.' },
      { kind: 'fail', text: 'Everyone watching the most likely door. Cover the unlikely one; that is where a good team comes from.' },
      { kind: 'h', text: 'E. Sound denial' },
      { kind: 'p', text: 'When the rush is close, stop moving. Footsteps are the largest information leak in the game. Used positively, a deliberate noise pulls a rush into the lane you have prepared.' },
      { kind: 'h', text: 'F. Vehicle-rush counter' },
      { kind: 'p', text: 'Two players shoot the vehicle — driver first, then the engine. Two hold the dismount side pre-aimed. Molotov the dismount point if you have the throw. The dismount is a second and a half where all four enemies are stationary and grouped.' },
      { kind: 'fail', text: 'All four unloading into the car body. It absorbs the magazine and you are all reloading together.' },
      { kind: 'h', text: 'G. Knock management' },
      { kind: 'rule', text: 'Do not chase the knock. Hold the revive angle. A downed enemy is bait; the revive is where the second and third kills come from. And when you knock someone, move immediately — they know where the shot came from.' },
      { kind: 'h', text: 'H. Refusing the fight' },
      { kind: 'rule', text: 'If you cannot get all four players out, healed, and into the next zone within the shrink timer, do not take the fight. This is where circle reading pays for itself.' },
      { kind: 'h', text: 'Five habits that lose defended compounds' },
      { kind: 'li', text: 'Healing during the rush — you are out of the fight for six to eight seconds.' },
      { kind: 'li', text: 'All four peeking the same window.' },
      { kind: 'li', text: 'Reviving in the open, in line of sight, under fire.' },
      { kind: 'li', text: 'Over-rotating to the first sound. That is often the distraction.' },
      { kind: 'li', text: 'Reloading together. Stagger it; someone is always loaded.' },
    ],
  },
  {
    title: 'The 1v4 clutch',
    blocks: [
      { kind: 'rule', text: 'You cannot win a 1v4. You can win four 1v1s. Every rule below converts the first into the second.' },
      { kind: 'p', text: 'The loop: assess, reposition to a one-way hold, go silent, wait for the commit, take the duel, reposition, punish the revive, repeat.' },
      { kind: 'li', text: 'Read the situation before you move. Four players caught outside the zone is a waiting game you are already winning.' },
      { kind: 'li', text: 'Get to a position with one approach, so their numbers cannot be applied at once.' },
      { kind: 'li', text: 'Silence. Stop moving entirely. Most 1v4 losses are a solo player repositioning at the wrong moment and being heard.' },
      { kind: 'li', text: 'Let them commit. Squads hunting one player push staggered. Wait for the first man past his cover.' },
      { kind: 'li', text: 'Reposition after every engagement. The remaining three know your window.' },
      { kind: 'li', text: 'Punish revives, never chase knocks. One knock becomes two if you hold the angle on the body.' },
      { kind: 'li', text: 'Use the zone as your fourth teammate. If you are in and they are not, do nothing.' },
      { kind: 'li', text: 'Smoke is for crossing and breaking, not for pushing.' },
      { kind: 'li', text: 'Heal only after you have broken line of sight and moved.' },
      { kind: 'li', text: 'Third parties are your ally. Position so they contact the enemy squad, not you.' },
      { kind: 'h', text: 'When to invert' },
      { kind: 'p', text: 'Go aggressive when the zone will force you out anyway, when they have located you and are setting up with utility, or when you are low enough that holding only delays the loss. Then flank wide and hit them while they watch your last known position.' },
      { kind: 'h', text: 'Change your loadout' },
      { kind: 'rule', text: 'Your team loadout and your clutch loadout are not the same loadout. When your last teammate goes down, if a second AR or an SMG is within reach, swapping your marksman weapon for it is usually worth the four seconds. See the Combat math module for why.' },
    ],
  },
  {
    title: 'Erangel — 8×8 km, three of six matches',
    blocks: [
      { kind: 'p', text: 'The control map. Compounds sit 200–400 m apart with usable cover between, so fights happen at mid range and positioning beats raw aim. The most balanced map in the pool and the one where discipline compounds most reliably.' },
      { kind: 'p', text: 'The Pochinki–School–Rozhok triangle is the most valuable real estate in most matches. Georgopol gives the container yard and apartments in the north; Mylta, Mylta Power and Novorepnoye anchor the east. Military Base holds excellent loot behind a bad commitment — the bridges are killing grounds.' },
      { kind: 'rule', text: 'Pochinki-style houses have two ground entrances plus a staircase — one too many to hold alone. Take two adjacent houses and cross their doorways.' },
      { kind: 'p', text: 'The real defensive terrain is not the buildings. It is the stone walls, treelines and ridges between compounds: cover with sightlines and no doors to breach. In the Georgopol stacks sound is unreliable and vertical angles dominate; hold the top with a teammate watching the climb.' },
      { kind: 'p', text: 'Loadout: M416 plus Mini14 or SLR. An AKM or M762 on the entry player for Pochinki density. Bolt-actions matter less here than on the other two maps.' },
    ],
  },
  {
    title: 'Miramar — 8×8 km, two of six matches',
    blocks: [
      { kind: 'rule', text: 'On Miramar you fight for terrain, not for buildings. A hill with rocks beats most compounds: elevation, cover and sightlines without giving the enemy a door.' },
      { kind: 'p', text: 'Pecado sits centre with the boxing gym and casino. Hacienda del Patrón is the strongest single elevated compound. Los Leones is the largest urban area; San Martín, El Pozo, Chumacera, Impala and Campo Militar fill out the rest.' },
      { kind: 'p', text: 'Rushes arrive by vehicle because crossing open ground on foot against a set squad does not work. Run the vehicle-counter split without exception.' },
      { kind: 'rule', text: 'Take the hill that has a back exit. A hill with no retreat is a trap the moment the zone pulls away, and Miramar zones move further than they look.' },
      { kind: 'p', text: 'Vehicles are not optional — keep one alive into the late circles and watch fuel. Route through valleys and behind ridges, not along open roads. Smoke is worth more here than anywhere else: it is the only cover in the places you must cross.' },
      { kind: 'p', text: 'Loadout: the map where snipers earn their slot. M416 plus Kar98k or M24, or plus an SLR for sustained pressure.' },
    ],
  },
  {
    title: 'Rondo — 8×8 km, one of six matches',
    blocks: [
      { kind: 'p', text: 'The largest playable landmass and the most varied. South-west is lakes and bamboo — dense, close-quarters. North-east is ridges — open, elevated, Miramar-like. Jadena City in the south-east is vertical urban warfare. One map containing three different games.' },
      { kind: 'p', text: 'Major points: Jadena City, NEOX Factory, the Stadium and Test Track, Mey Ran, Yu Lin and Rin Jiang. Smaller: Tin Long Garden, Jao Tin, Hung Shan, Dan Ching, Nan Chuan, Hemay Town, Fong Tun, Long Ho, Mu Ho Pan, Bei Li and Rai An.' },
      { kind: 'p', text: 'Rondo runs two starting aircraft, so drop contests are far less predictable. Scout both flight paths — the compound you thought was uncontested may sit under the second plane.' },
      { kind: 'rule', text: 'Destructible bamboo is the defining feature. It looks like cover and is not — a frag or a vehicle clears it. Never trust it defensively, and pre-clear it offensively to open a fire lane before you commit.' },
      { kind: 'p', text: 'Anti-rush depends on which terrain your zone lands in, which is why Rondo punishes rigid teams. In Jadena, hold the upper floor with separate players watching the escalator and the stairwell. In the bamboo, tight crossfires and molotovs on approach lanes. On the ridges, apply the Miramar playbook wholesale.' },
      { kind: 'p', text: 'Loadout: the most flexible of the three. M416 plus a DMR as the base, then adapt — a close-range option if the zone pulls to Jadena or bamboo, a bolt-action if it pulls to the ridges. The JS9 is a real option inside Jadena and nowhere else.' },
    ],
  },
  {
    title: 'Drills',
    blocks: [
      { kind: 'li', text: 'Pre-aim: TDM, hold one fixed angle for a whole round, never scan. Score only duels on that angle.' },
      { kind: 'li', text: 'Crossfire: custom room, 2v2 in one compound. Attackers must breach, defenders hold two structures.' },
      { kind: 'li', text: 'Utility: land ten molotovs in a doorway from ten positions, then ten smokes covering a fixed 40 m crossing.' },
      { kind: 'li', text: 'Vehicle counter: one squad rushes by car, one defends with the two-and-two split. Rotate roles.' },
      { kind: 'li', text: '1v4: four teammates push one player in a fixed compound. Survive ninety seconds rather than trying to win. Run it once with the team loadout and once with a second AR, opponents in Level 3 armour both times.' },
      { kind: 'li', text: 'Time-to-kill: Training Grounds, ten trials per gun at fixed distances, take the median. Repeat after every patch.' },
    ],
  },
];
